import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  validateEmail,
  validateAmount,
  validateTextLength,
  validateRequisites,
  validateWithdrawalInput,
  type WithdrawalInput,
} from '../../utils/validation';

/**
 * Feature: premium-redesign, Property 13: Input validation correctness
 * Validates: Requirements 7.3
 *
 * For any input string or number, the validation functions SHALL correctly classify:
 * - Email: valid if and only if it matches RFC 5322 simplified pattern
 * - Amount: valid if and only if 0.01 ≤ value ≤ 999999.99
 * - Text length: valid if and only if length ≤ 1000 characters
 * - Requisites: valid if and only if length ≥ 5 characters
 */
describe('Property 13: Input validation correctness', () => {
  describe('validateAmount', () => {
    it('returns true for any number in [0.01, 999999.99]', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0.01, max: 999999.99, noNaN: true }),
          (amount) => {
            expect(validateAmount(amount)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns false for numbers below 0.01', () => {
      fc.assert(
        fc.property(
          fc.double({ min: -1e10, max: 0.009999, noNaN: true }),
          (amount) => {
            expect(validateAmount(amount)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns false for numbers above 999999.99', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 999999.991, max: 1e10, noNaN: true }),
          (amount) => {
            expect(validateAmount(amount)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns false for NaN and Infinity', () => {
      expect(validateAmount(NaN)).toBe(false);
      expect(validateAmount(Infinity)).toBe(false);
      expect(validateAmount(-Infinity)).toBe(false);
    });
  });

  describe('validateTextLength', () => {
    it('returns true for strings with length ≤ 1000', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 0, maxLength: 1000 }),
          (text) => {
            expect(validateTextLength(text)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns false for strings with length > 1000', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 1001, maxLength: 2000 }),
          (text) => {
            expect(validateTextLength(text)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('validateRequisites', () => {
    it('returns true for strings with length ≥ 5', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 5, maxLength: 200 }),
          (value) => {
            expect(validateRequisites(value)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns false for strings with length < 5', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 0, maxLength: 4 }),
          (value) => {
            expect(validateRequisites(value)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('validateEmail', () => {
    it('returns true for well-formed emails generated by fc.emailAddress()', () => {
      fc.assert(
        fc.property(
          fc.emailAddress(),
          (email) => {
            expect(validateEmail(email)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns false for arbitrary strings without @ symbol', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 1 }).filter((s) => !s.includes('@')),
          (notEmail) => {
            expect(validateEmail(notEmail)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('validateWithdrawalInput', () => {
    const validMethod = fc.constantFrom<WithdrawalInput['method']>('sbp', 'card', 'lolz', 'yoomoney');
    const validAmount = fc.double({ min: 0.01, max: 999999.99, noNaN: true });
    const validRequisites = fc.string({ minLength: 5, maxLength: 100 });
    const validBankName = fc.string({ minLength: 1, maxLength: 50 });

    it('returns valid:true only when all individual validations pass', () => {
      fc.assert(
        fc.property(
          validAmount,
          validMethod,
          validRequisites,
          validBankName,
          (amount, method, requisites, bankName) => {
            const input: WithdrawalInput = {
              amount,
              method,
              requisites,
              ...(method === 'sbp' ? { bankName } : {}),
            };
            const result = validateWithdrawalInput(input);

            // All individual validations should pass
            const amountValid = validateAmount(amount);
            const requisitesValid = validateRequisites(requisites);
            const bankNameValid = method !== 'sbp' || (!!bankName && bankName.trim().length > 0);

            if (amountValid && requisitesValid && bankNameValid) {
              expect(result.valid).toBe(true);
              expect(Object.keys(result.errors)).toHaveLength(0);
            }
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns valid:false when amount is invalid', () => {
      fc.assert(
        fc.property(
          fc.double({ min: -1e6, max: 0.009, noNaN: true }),
          validMethod,
          validRequisites,
          validBankName,
          (amount, method, requisites, bankName) => {
            const input: WithdrawalInput = {
              amount,
              method,
              requisites,
              ...(method === 'sbp' ? { bankName } : {}),
            };
            const result = validateWithdrawalInput(input);
            expect(result.valid).toBe(false);
            expect(result.errors).toHaveProperty('amount');
          }
        ),
        { numRuns: 100 }
      );
    });

    it('returns valid:false when requisites are too short', () => {
      fc.assert(
        fc.property(
          validAmount,
          validMethod,
          fc.string({ minLength: 0, maxLength: 4 }),
          validBankName,
          (amount, method, shortRequisites, bankName) => {
            const input: WithdrawalInput = {
              amount,
              method,
              requisites: shortRequisites,
              ...(method === 'sbp' ? { bankName } : {}),
            };
            const result = validateWithdrawalInput(input);
            expect(result.valid).toBe(false);
            expect(result.errors).toHaveProperty('requisites');
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});
